--- 
title: "Data Mining with R"
author: "Bradley Boehmke"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: references.bib
biblio-style: apalike
link-citations: yes
github-repo: bradleyboehmke/uc-bana-7025
twitter-handle: bradleyboehmke
description: "Master the art of data wrangling & analysis with the R programming language."
---

`r if (knitr::is_latex_output()) '<!--'` 

# Syllabus {-}

```{block, type = "note"}
This is the primary "textbook" for the *Machine Learning* section of the UC BANA 4080 Data Mining course. The following is a truncated syllabus; for the full syllabus along with complete course content please visit the online course content in [Canvas](https://uc.instructure.com/). 
```

Welcome to ___Data Mining with R___! This course provides an intensive, hands-on introduction to data mining and analysis techniques. You will learn the fundamental skills required to extract informative attributes, relationships, and patterns from data sets. You will gain hands-on experience with exploratory data analysis, data visualization, unsupervised learning techniques such as clustering and dimension reduction, and supervised learning techniques such as linear regression, regularized regression, decision trees, random forests, and more! You will also be exposed to some more advanced topics such as ensembling techniques, deep learning, model stacking, and model interpretation. Together, this will provide you with a solid foundation of tools and techniques applied in organizations to aid modern day data-driven decision making.

```{block, type='video'}
Check out the video in the "Overview of Course" module on Canvas for a quick introduction to this course.
```


## Learning Objectives {-}

Upon successfully completing this course, you will be able to:

* Apply data wrangling techniques to manipulate and prepare data for analysis.
* Use exploratory data analysis and visualization to provide descriptive insights of data.
* Apply common unsupervised learning algorithms to find common groupings of observations and features in a given dataset.
* Describe and apply a sound analytic modeling process.
* Apply, compare, and contrast various predictive modeling techniques.
* Have the resources and understanding to continue advancing your data mining and analysis capabilities.

...all with R!

```{block, type = "note"}
This course assumes no prior knowledge of R. Experience with programming concepts or another programming language will help, but is not required to understand the material. 
```

## Material {-}

This course is split into two main sections - <u>***Data Wrangling***</u> and <u>***Machine Learning***</u>. The data wrangling section will provide you the fundamental skills required to acquire, munge, transform, manipulate, and visualize data in a computing environment that fosters reproducibility. The primary course material for this section is provided via this [free online book](https://bradleyboehmke.github.io/uc-bana-7025/). 

The second section focused on machine learning section will expose you to several algorithms to identify hidden patterns and relationships within your data. The primary course material for this part of the course is provided via this [free online book](https://bradleyboehmke.github.io/uc-bana-4080/).  There will also be recorded lectures and additional supplementary resources provided via Canvas. 

## Class Structure {-}

__Modules__: For this class each module is covered over the course of week. In the "Overview" section for each module you will find overall learning objectives, a short description of the learning content covered in that module, along with all tasks that are required of you for that module (i.e. quizzes, lab). Each module will have two or more primary lessons and associated quizzes along with a lab.

__Lessons__: For each lesson you will read and work through the tutorial. Short videos will be sprinkled throughout the lesson to further discuss and reinforce lesson concepts. Each lesson will have various "TODO" exercises throughout, along with end-of-lesson exercises. I highly recommend you work through these exercises as they will prepare you for the quizzes, labs, and project work.

__Quizzes__: There will be a short quiz associated with _each lesson_. These quizzes will be hosted in the course website on Canvas. Please check Canvas for due dates for these quizzes.

__Labs__: There will be a lab associated with _each module_. For these labs students will be guided through a case study step-by-step. The aim is to provide a detailed view on how to manage a variety of complex real-world data; how to convert real problems into data wrangling and analysis problems; and to apply R to address these problems and extract insights from the data. These labs will be provided via the course website on Canvas and the submission of these labs will also be done through the course website on Canvas. Please check Canvas for due dates for these labs.

__Projects__: There will be two projects designed for you to put to work the tools and knowledge that you gain throughout this course. This provides you with multiple benefits.  
- It will provide you with more experience using data wrangling tools on real life data sets.
- It helps you become a self-directed learner. As a data scientist, a large part of your job is to self-direct your learning and interests to find unique and creative ways to find insights in data.
- It starts to build your data science portfolio. Establishing a data science portfolio is a great way to show potential employers your ability to work with data.


## Schedule {-}

```{block, type = "note"}
See the [Canvas](https://uc.instructure.com/) course webpage for a detailed schedule with due dates for quizzes, labs, etc.
```

| Module        | Description                                         |
|:-------------:|:----------------------------------------------------|
|               | **DATA WRANGLING**                                  |
| **1**         | **Introduction**                                    |
|               | R fundamentals & the Rstudio IDE                    |
|               | Deeper understanding of vectors                     |
| **2**         | **Reproducible Documents and Importing Data**       |
|               | Managing your workflow and reproducibility          |
|               | Data structures & importing data                    |
| **3**         | **Tidy Data and Data Manipulation**                 |
|               | Data manipulation & summarization                   |
|               | Tidy data                                           |
| **4**         | **Relational Data and More Tidyverse Packages**     |
|               | Relational data                                     |
|               | Leveraging the Tidyverse to text & date-time data   |
| **5**         | **Data Visualization & Exploration**                |
|               | Data visualization                                  |
|               | Exploratory data analysis                           |
| **6**         | **Creating Efficient Code in R**                    |
|               | Control statements & iteration                      |
|               | Writing functions                                   |
|               | **MACHINE LEARNING**                                  |
| **7**         | **Introduction to Applied Modeling**                |
|               | Introduction to tidymodels                          |
|               | Feature engineering & model evaluation/selection    |
| **8**         | **First regression models**                         |
|               | Ordinary least squares (OLS)                        |
|               | OLS cousins                                         |
| **9**         | **First classification models**                     |
|               | Logistic regression                                 |
|               | Assessing classification models                     |
| **10**         | **More regression cousins**                         |
|               | Regularized regression                              |
|               | Multi-adaptive Regression Splines (MARS)            |
| **11**         | **Venturing away from linearity**                   |
|               | K-Nearest neighbor                                  |
|               | Decision trees                                      |
| **12**        | **Ensembling trees**                                |
|               | Bagging                                             |
|               | Random forests                                      |
| **13**        | **Ensembling trees continued**                      |
|               | Gradient boosting                                   |
|               | XGBoost and other variants                          |
| **14**        | **Deep learning**                                   |
|               | Feedforward neural nets                             |
|               | A survey of deep learning extensions                |
| **15**        | **Unsupervised Learning** |
|               | Clustering.                                         |
|               | Dimension reductions                                |

## Conventions used in this book {-}

The following typographical conventions are used in this book:

* ___strong italic___: indicates new terms,
* __bold__: indicates package & file names,
* `inline code`: monospaced highlighted text indicates functions or other commands that could be typed literally by the user,
* code chunk: indicates commands or other text that could be typed literally by the user

```{r, first-code-chunk, collapse=TRUE}
1 + 2
```

In addition to the general text used throughout, you will notice the following cells that provide additional context for improved learning:

```{block, type = "video"}
A video demonstrating this topic is available in Canvas.
```

```{block, type = "tip"}
A tip or suggestion that will likely produce better results.
```

```{block, type = "note"}
A general note that could improve your understanding but is not required for the course requirements.
```

```{block, type = "warning"}
Warning or caution to look out for.
```

```{block, type = "todo"}
Knowledge check exercises to gauge your learning progress.
```

## Feedback {-}

To report errors or bugs that you find in this course material please post an issue at https://github.com/bradleyboehmke/uc-bana-4080/issues. For all other communication be sure to use Canvas or the university email. 

```{block, type = "tip"}
When communicating with me via email, please always include **BANA4080** in the subject line.
```

## Acknowledgements {-}

This course and its materials have been influenced by the following resources:

- Jenny Bryan, [STAT 545: Data wrangling, exploration, and analysis with R](http://stat545.com/)
- Garrett Grolemund & Hadley Wickham, [R for Data Science](http://r4ds.had.co.nz/index.html)
- Stephanie Hicks, [Statistical Computing](https://www.stephaniehicks.com/jhustatcomputing2021/)
- Chester Ismay & Albert Kim, [ModernDive](https://moderndive.netlify.app/index.html)
- Alex Douglas et al., [An Introduction to R](https://intro2r.com/)
- Brandon Greenwell, [Hands-on Machine Learning with R](https://bradleyboehmke.github.io/HOML/)
