<!DOCTYPE html>
<html lang="en"><head>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="w10_tuesday_files/libs/clipboard/clipboard.min.js"></script>
<script src="w10_tuesday_files/libs/quarto-html/tabby.min.js"></script>
<script src="w10_tuesday_files/libs/quarto-html/popper.min.js"></script>
<script src="w10_tuesday_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="w10_tuesday_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="w10_tuesday_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="w10_tuesday_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="w10_tuesday_files/libs/quarto-contrib/quarto-timer-1.0.0/timer.js"></script>
<link href="w10_tuesday_files/libs/quarto-contrib/quarto-timer-1.0.0/timer.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <title>Week 10 – From Numbers to Categories</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="w10_tuesday_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="w10_tuesday_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="w10_tuesday_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="styles.css">
  <link href="w10_tuesday_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="w10_tuesday_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="w10_tuesday_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="w10_tuesday_files/libs/revealjs/plugin/appearance/appearance.css" rel="stylesheet">
  <link href="w10_tuesday_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>
  
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="images/classification-background.png" data-background-opacity="1.00" data-background-size="cover" class="quarto-title-block center">
  <h1 class="title">Week 10 – From Numbers to Categories</h1>
  <p class="subtitle">Introduction to Logistic Regression &amp; Classification Evaluation</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="welcome-to-week-10" class="slide level2 smaller">
<h2>Welcome to Week 10</h2>
<ul>
<li><p>Quick overview of today’s plan:</p>
<ul>
<li>Understand the difference between regression and classification</li>
<li>Introduction to logistic regression and why it works for categories</li>
<li>How to interpret model results (coefficients and probabilities)</li>
<li>Why accuracy isn’t enough and what metrics actually matter</li>
<li>Business scenarios: choosing the right evaluation approach</li>
</ul></li>
</ul>
</section>
<section>
<section id="discussion-homework-questions" class="title-slide slide level1 center" data-background="#43464B">
<h1>Discussion: Homework &amp; Questions</h1>

</section>
<section id="questions-from-week-9" class="slide level2 smaller">
<h2>Questions from Week 9?</h2>
<ul>
<li>Machine learning fundamentals?</li>
<li>Supervised vs.&nbsp;unsupervised learning?</li>
<li>Correlation vs.&nbsp;linear regression?</li>
<li>Anything confusing in the quiz or readings?</li>
<li>Time to ask!</li>
</ul>
<div class="fragment">
<div class="columns">
<div class="column" style="width:70%;">
<div class="callout callout-none no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Activity</strong></p>
</div>
<div class="callout-content">
<p>Converse with your neighbor and identify…</p>
<ul>
<li>1 concept from last week that you thought was well explained</li>
<li>1 concept that is still confusing</li>
</ul>
</div>
</div>
</div>
</div><div class="column" style="width:30%;">
<center>
<div id="2minWaiting">

</div>
<script src="_extensions/produnis/timer/timer.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        initializeTimer("2minWaiting", 120, "slide"); 
    });
</script>
</center>
</div></div>
</div>
</section></section>
<section>
<section id="predicting-numbers-categories" class="title-slide slide level1 center" data-background="#43464B">
<h1>Predicting <del>Numbers</del> Categories</h1>

</section>
<section id="not-every-business-question-is-about-numbers" class="slide level2 smaller">
<h2>Not Every Business Question is About Numbers</h2>
<p><strong>Week 9 Review:</strong> We’ve been predicting continuous values…</p>
<ul>
<li><em>How much revenue will we generate?</em></li>
<li><em>What price should we set for this product?</em></li>
<li><em>What will our customer lifetime value be?</em></li>
</ul>
<p><strong>Today’s New Challenge:</strong> Many critical decisions involve categories…</p>
<ul>
<li><em>Will this customer default on their loan?</em> (Yes/No)</li>
<li><em>Is this email spam?</em> (Spam/Not Spam)</li>
<li><em>Should we approve this application?</em> (Approve/Deny)</li>
<li><em>Will this marketing campaign succeed?</em> (Success/Failure)</li>
</ul>
</section>
<section id="pop-quiz-regression-vs.-classification" class="slide level2 smaller">
<h2>Pop Quiz: Regression vs.&nbsp;Classification</h2>
<p>Rapid fire, classify each as <strong>REGRESSION</strong> or <strong>CLASSIFICATION:</strong></p>
<ul>
<li class="fragment">Predicting how many units of a product will sell next month</li>
<li class="fragment">Determining if a customer will purchase a premium subscription</li>
<li class="fragment">Estimating insurance claim amounts in dollars</li>
<li class="fragment">Deciding whether to show a promotional offer to a customer</li>
<li class="fragment">Forecasting quarterly revenue</li>
<li class="fragment">Classifying support tickets as “Technical” or “Billing”</li>
<li class="fragment">Predicting employee salary based on experience and education</li>
<li class="fragment">Determining if a loan application should be approved or denied</li>
<li class="fragment">Estimating the number of website visitors next month</li>
<li class="fragment">Classifying emails as “Spam”, “Important”, or “General”</li>
</ul>
</section>
<section id="think-pair-share-regression-vs.-classification" class="slide level2 smaller">
<h2>Think-Pair-Share: Regression vs.&nbsp;Classification</h2>
<div class="columns">
<div class="column" style="width:70%;">
<p><strong>In your groups, discuss where classification models are already impacting your daily lives:</strong></p>
<p>Examples might include:</p>
<ul>
<li>Netflix recommending movies you’ll like,</li>
<li>sports betting apps predicting which team will win,</li>
<li>social media deciding what posts to show you,</li>
<li>your bank determining whether to approve a purchase.</li>
</ul>
<p><strong>Share 2-3 examples with your group and discuss:</strong></p>
<ul>
<li>What categories is the model predicting?</li>
<li>How does this affect your experience as a user?</li>
</ul>
</div><div class="column" style="width:30%;">
<center>
<div id="5minClassify">

</div>
<script src="_extensions/produnis/timer/timer.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        initializeTimer("5minClassify", 300, "slide"); 
    });
</script>
</center>
</div></div>
</section>
<section id="why-linear-regression-fails" class="slide level2 smaller">
<h2>Why Linear Regression Fails</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Problems with Linear Regression for Classification:</strong></p>
<ul>
<li><strong>Invalid predictions</strong>: Can predict values like -0.3 or 1.8 for Yes/No questions</li>
<li><strong>Straight line assumption</strong>: Real classification relationships follow S-shaped curves</li>
<li><strong>No probability interpretation</strong>: A prediction of 0.7 doesn’t clearly mean 70% chance</li>
</ul>
<p><strong>Example:</strong> Credit default prediction</p>
<ul>
<li>Linear regression might predict 1.3 for “will default”</li>
<li>What does 1.3 mean? 130% chance of default? Impossible!</li>
</ul>
</div><div class="column" style="width:40%;">
<div id="32b95b92" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="w10_tuesday_files/figure-revealjs/cell-2-output-1.png" class="quarto-figure quarto-figure-center" width="526" height="302"></p>
</figure>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Show students that linear regression creates a straight line that can go beyond 0 and 1, while logistic regression creates an S-shaped curve that stays between valid probability bounds.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="logistic-regression-the-s-shaped-solution" class="title-slide slide level1 center" data-background="#43464B">
<h1>Logistic Regression: The S-Shaped Solution</h1>

</section>
<section id="the-logistic-function" class="slide level2 smaller">
<h2>The Logistic Function</h2>
<p><strong>Key Innovation:</strong> Transform linear predictions into probabilities using the logistic function:</p>
<p><span class="math display">\[p = \frac{1}{1 + e^{-z}}\]</span></p>
<p>where <span class="math inline">\(z = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + ...\)</span></p>
<p><br></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Does <span class="math inline">\(z\)</span> look familiar? 🤔</p>
</div>
</div>
</div>
<div class="fragment">
<p><br></p>
<p><em>This equation takes any number (our risk score <span class="math inline">\(z\)</span>) and squeezes it between 0 and 1 to create a valid probability.</em></p>
</div>
</section>
<section id="creates-valid-probabilities" class="slide level2 smaller scrollable">
<h2>Creates Valid Probabilities</h2>
<p><strong>Magic Properties:</strong></p>
<ul>
<li><strong>Always between 0 and 1</strong> - perfect for probabilities!</li>
<li><strong>S-shaped curve</strong> - captures realistic business relationships</li>
<li><strong>Smooth transitions</strong> - gradual probability changes, not jumps</li>
<li><strong>50% at center</strong> - when z = 0, probability = exactly 50%</li>
</ul>
<div id="cc7d59f8" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="w10_tuesday_files/figure-revealjs/cell-3-output-1.png" class="quarto-figure quarto-figure-center" width="663" height="376"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="using-the-s-curve-for-business-decisions" class="slide level2 smaller">
<h2>Using the S-Curve for Business Decisions</h2>
<p>The S-shaped curve gives us <strong>two powerful tools</strong> for business decision-making:</p>
<p><strong>1. Probability Estimates:</strong> Get the exact chance an event will happen (0-100%)</p>
<p><strong>2. Binary Classifications:</strong> Make yes/no decisions using the 50% threshold</p>
<div id="a0071e76" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="w10_tuesday_files/figure-revealjs/cell-4-output-1.png" class="quarto-figure quarto-figure-center" width="812" height="449"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Insight:</strong> Every prediction gives you a probability between 0-100%, but the 50% threshold determines the final yes/no decision.</p>
</section>
<section id="business-context-activity" class="slide level2 smaller">
<h2>Business Context Activity</h2>
<p>Now that you understand logistic regression gives us both probability estimates AND classifications, let’s think about when each is most valuable:</p>
<div class="columns">
<div class="column" style="width:70%;">
<p><strong>In your groups, identify:</strong></p>
<ol type="1">
<li><strong>2 business scenarios where you’d want PROBABILITY ESTIMATES</strong> (exact percentages)</li>
<li><strong>2 business scenarios where you’d want CLASSIFICATIONS</strong> (yes/no decisions)</li>
</ol>
<p><strong>Then discuss:</strong> Why do you think probability estimates are better for some situations while classifications are better for others?</p>
<p><strong>Think about:</strong> Risk assessment, decision automation, customer communication, regulatory requirements, etc.</p>
</div><div class="column" style="width:30%;">
<center>
<div id="4minProbVsClass">

</div>
<script src="_extensions/produnis/timer/timer.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        initializeTimer("4minProbVsClass", 240, "slide"); 
    });
</script>
</center>
</div></div>
<p>Then we’ll share examples with the class…</p>
</section>
<section id="building-a-logistic-regression-model" class="slide level2 smaller scrollable">
<h2>Building a Logistic Regression Model</h2>
<p><strong>Step 1:</strong> Load and explore the ISLP Default dataset</p>
<div id="7aba73c5" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="im">from</span> ISLP <span class="im">import</span> load_data</span>
<span id="cb1-2"><a href=""></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a><span class="co"># Load the Default dataset</span></span>
<span id="cb1-5"><a href=""></a>Default <span class="op">=</span> load_data(<span class="st">'Default'</span>)</span>
<span id="cb1-6"><a href=""></a></span>
<span id="cb1-7"><a href=""></a>Default[[<span class="st">'default'</span>, <span class="st">'balance'</span>, <span class="st">'income'</span>]].head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">default</th>
<th data-quarto-table-cell-role="th">balance</th>
<th data-quarto-table-cell-role="th">income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>No</td>
<td>729.526495</td>
<td>44361.625074</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>No</td>
<td>817.180407</td>
<td>12106.134700</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>No</td>
<td>1073.549164</td>
<td>31767.138947</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>No</td>
<td>529.250605</td>
<td>35704.493935</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>No</td>
<td>785.655883</td>
<td>38463.495879</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="fragment">
<p><strong>Step 2:</strong> Fit the logistic regression model</p>
<div id="6e5583d2" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2" data-code-line-numbers="|1,5,8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb2-2"><a href=""></a></span>
<span id="cb2-3"><a href=""></a><span class="co"># Prepare features (balance and income) and target</span></span>
<span id="cb2-4"><a href=""></a>X <span class="op">=</span> Default[[<span class="st">'balance'</span>, <span class="st">'income'</span>]]</span>
<span id="cb2-5"><a href=""></a>y <span class="op">=</span> (Default[<span class="st">'default'</span>] <span class="op">==</span> <span class="st">'Yes'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb2-6"><a href=""></a></span>
<span id="cb2-7"><a href=""></a><span class="co"># Fit logistic regression model</span></span>
<span id="cb2-8"><a href=""></a>model <span class="op">=</span> LogisticRegression()</span>
<span id="cb2-9"><a href=""></a>model.fit(X, y)</span>
<span id="cb2-10"><a href=""></a></span>
<span id="cb2-11"><a href=""></a><span class="co"># Extract the coefficients</span></span>
<span id="cb2-12"><a href=""></a>intercept <span class="op">=</span> model.intercept_[<span class="dv">0</span>]</span>
<span id="cb2-13"><a href=""></a>balance_coef <span class="op">=</span> model.coef_[<span class="dv">0</span>][<span class="dv">0</span>]</span>
<span id="cb2-14"><a href=""></a>income_coef <span class="op">=</span> model.coef_[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb2-15"><a href=""></a></span>
<span id="cb2-16"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Intercept: </span><span class="sc">{</span>intercept<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb2-17"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Balance coefficient: </span><span class="sc">{</span>balance_coef<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb2-18"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Income coefficient: </span><span class="sc">{</span>income_coef<span class="sc">:.6f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept: -11.540468
Balance coefficient: 0.005647
Income coefficient: 0.000021</code></pre>
</div>
</div>
<p><strong>So, what do these coefficients mean?</strong> 🤔</p>
</div>
</section>
<section id="probability-odds-and-log-odds" class="slide level2 smaller">
<h2>Probability, Odds, and Log-Odds</h2>
<p>To interpret logistic regression coefficients, we need three related concepts:</p>
<ul>
<li><strong>Probability:</strong> The familiar 0-100% chance something happens</li>
<li><strong>Odds:</strong> Ratio of probability it happens vs.&nbsp;doesn’t happen (probability / (1 - probability))</li>
<li><strong>Log-Odds:</strong> Natural logarithm of the odds</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Probability</strong></th>
<th><strong>Odds</strong></th>
<th><strong>Log-Odds</strong></th>
<th><strong>Business Interpretation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10%</td>
<td>0.11</td>
<td>-2.20</td>
<td>Very unlikely event</td>
</tr>
<tr class="even">
<td>25%</td>
<td>0.33</td>
<td>-1.10</td>
<td>Unlikely event</td>
</tr>
<tr class="odd">
<td>50%</td>
<td>1.00</td>
<td>0.00</td>
<td>Neutral (decision boundary)</td>
</tr>
<tr class="even">
<td>75%</td>
<td>3.00</td>
<td>1.10</td>
<td>Likely event</td>
</tr>
<tr class="odd">
<td>90%</td>
<td>9.00</td>
<td>2.20</td>
<td>Very likely event</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key insight:</strong></p>
</div>
<div class="callout-content">
<p>Logistic regression coefficients represent changes in <strong>log-odds</strong>, not probability!</p>
</div>
</div>
</div>
</section>
<section id="interpreting-our-coefficients" class="slide level2 smaller scrollable">
<h2>Interpreting Our Coefficients</h2>
<p>Now we can understand what our coefficients mean:</p>
<p><strong>Intercept (-11.540468):</strong></p>
<ul>
<li>When balance = $0 and income = $0, the log-odds of default = -11.54</li>
<li>This means very low baseline probability of default (~0.000973%)</li>
</ul>
<p><strong>Balance coefficient (0.005647):</strong></p>
<ul>
<li>For each $1 increase in balance, log-odds increase by 0.005647</li>
<li>For each $1,000 increase in balance, log-odds increase by ~5.6 Probability increases ~95%</li>
<li><strong>Positive coefficient = higher balance increases default risk</strong> ✓</li>
</ul>
<p><strong>Income coefficient (0.000021):</strong></p>
<ul>
<li>For each $1 increase in income, log-odds increase by 0.000021</li>
<li>For each $10,000 increase in income, log-odds increase by ~0.21</li>
<li>Probability increases by only ~5%</li>
<li><strong>Tiny positive coefficient = income has minimal effect on default risk</strong></li>
</ul>
<p><strong>Business Translation:</strong></p>
<ul>
<li><strong>Balance is the primary driver</strong> of default risk</li>
<li><strong>Income has almost no effect</strong> once we account for balance</li>
<li>A customer with $2,000 balance is much riskier than one with $1,000 balance, regardless of income</li>
</ul>
</section>
<section id="from-coefficients-to-predictions" class="slide level2 smaller scrollable">
<h2>From Coefficients to Predictions</h2>
<p><strong>Step 1:</strong> Use coefficients in the logistic function</p>
<div id="ff158b00" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-2"><a href=""></a></span>
<span id="cb4-3"><a href=""></a><span class="co"># Manual calculation for $1,500 balance, $50,000 income</span></span>
<span id="cb4-4"><a href=""></a>balance <span class="op">=</span> <span class="dv">1500</span></span>
<span id="cb4-5"><a href=""></a>income <span class="op">=</span> <span class="dv">50000</span></span>
<span id="cb4-6"><a href=""></a>log_odds <span class="op">=</span> <span class="op">-</span><span class="fl">11.540468</span> <span class="op">+</span> <span class="fl">0.005647</span> <span class="op">*</span> balance <span class="op">+</span> <span class="fl">0.000021</span> <span class="op">*</span> income</span>
<span id="cb4-7"><a href=""></a>probability_manual <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>log_odds))</span>
<span id="cb4-8"><a href=""></a></span>
<span id="cb4-9"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Manual calculation: </span><span class="sc">{</span>probability_manual<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Manual calculation: 0.1171</code></pre>
</div>
</div>
<p><strong>Step 2:</strong> Compare with scikit-learn</p>
<div id="91aebf5f" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href=""></a><span class="co"># Scikit-learn prediction (must include both features)</span></span>
<span id="cb6-2"><a href=""></a>customer_df <span class="op">=</span> pd.DataFrame({<span class="st">'balance'</span>: [<span class="dv">1500</span>], <span class="st">'income'</span>: [<span class="dv">50000</span>]})</span>
<span id="cb6-3"><a href=""></a>probability_sklearn <span class="op">=</span> model.predict_proba(customer_df)[:, <span class="dv">1</span>]</span>
<span id="cb6-4"><a href=""></a></span>
<span id="cb6-5"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Scikit-learn prediction: </span><span class="sc">{</span>probability_sklearn[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Scikit-learn prediction: 0.1162</code></pre>
</div>
</div>
<p><strong>Both give similar results for a customer with $1,500 balance and $50,000 income</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Small Differences Expected</strong></p>
</div>
<div class="callout-content">
<p>The manual calculation and scikit-learn prediction may differ slightly (e.g., 0.1171 vs 0.1162) due to rounding in the displayed coefficients. Scikit-learn uses the full precision coefficients internally.</p>
</div>
</div>
</div>
</section>
<section id="evaluating-model-performance" class="slide level2 smaller scrollable">
<h2>Evaluating Model Performance</h2>
<p>Now that we’ve built our model, let’s evaluate how well it performs on new data:</p>
<div id="e8c2abb0" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href=""></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb8-2"><a href=""></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score</span>
<span id="cb8-3"><a href=""></a></span>
<span id="cb8-4"><a href=""></a><span class="co"># Split data into training and test sets</span></span>
<span id="cb8-5"><a href=""></a>X <span class="op">=</span> Default[[<span class="st">'balance'</span>, <span class="st">'income'</span>]]</span>
<span id="cb8-6"><a href=""></a>y <span class="op">=</span> (Default[<span class="st">'default'</span>] <span class="op">==</span> <span class="st">'Yes'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb8-7"><a href=""></a></span>
<span id="cb8-8"><a href=""></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb8-9"><a href=""></a>    X, y, test_size<span class="op">=</span><span class="fl">0.3</span>, random_state<span class="op">=</span><span class="dv">42</span>, stratify<span class="op">=</span>y</span>
<span id="cb8-10"><a href=""></a>)</span>
<span id="cb8-11"><a href=""></a></span>
<span id="cb8-12"><a href=""></a><span class="co"># Train the model on training data</span></span>
<span id="cb8-13"><a href=""></a>model <span class="op">=</span> LogisticRegression()</span>
<span id="cb8-14"><a href=""></a>model.fit(X_train, y_train)</span>
<span id="cb8-15"><a href=""></a></span>
<span id="cb8-16"><a href=""></a><span class="co"># Make predictions on test data</span></span>
<span id="cb8-17"><a href=""></a>y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb8-18"><a href=""></a></span>
<span id="cb8-19"><a href=""></a><span class="co"># Calculate accuracy</span></span>
<span id="cb8-20"><a href=""></a>accuracy <span class="op">=</span> accuracy_score(y_test, y_pred)</span>
<span id="cb8-21"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Model Accuracy: </span><span class="sc">{</span>accuracy<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Accuracy: 97.1%</code></pre>
</div>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical Question</strong></p>
</div>
<div class="callout-content">
<p>With an accuracy of <strong>97%+</strong>, should we base our model’s performance solely on this metric?</p>
<p>Is this a good model for our business needs?</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="beyond-accuracy-why-97-can-be-terrible" class="title-slide slide level1 center" data-background="#43464B">
<h1>Beyond Accuracy: Why 97% Can Be Terrible</h1>

</section>
<section id="the-accuracy-trap" class="slide level2 smaller">
<h2>The Accuracy Trap</h2>
<p><strong>Shocking Example:</strong> Credit card fraud detection with 100,000 transactions:</p>
<ul>
<li><strong>Fraudulent transactions</strong>: 1,000 (1%)</li>
<li><strong>Legitimate transactions</strong>: 99,000 (99%)</li>
</ul>
<p><strong>Two models:</strong></p>
<ul>
<li><strong>Model A (Lazy)</strong>: Always predicts “legitimate” → <strong>99.0% accuracy</strong></li>
<li><strong>Model B (Smart)</strong>: Catches 80% of fraud, 2% false alarms → <strong>97.8% accuracy</strong></li>
</ul>
<p><strong>Which would you choose for your business?</strong></p>
<div class="fragment">
<p><br></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>The Problem:</strong> Model A provides ZERO business value but has higher accuracy!</p>
</div>
</div>
</div>
</div>
</section>
<section id="understanding-classification-errors" class="slide level2 smaller scrollable">
<h2>Understanding Classification Errors</h2>
<p><strong>The Confusion Matrix: Where Our Model Goes Wrong</strong></p>
<div id="629da504" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="w10_tuesday_files/figure-revealjs/cell-10-output-1.png" class="quarto-figure quarto-figure-center" width="581" height="565"></p>
</figure>
</div>
</div>
</div>
<p><strong>Why These Errors Matter:</strong></p>
<ul>
<li><strong>False Positives (FP) are harmful because:</strong>
<ul>
<li>Good customers get denied credit or charged higher rates</li>
<li>Customer frustration leads to churn and lost revenue</li>
<li>Wasted resources investigating “false alarms”</li>
</ul></li>
<li><strong>False Negatives (FN) are harmful because:</strong>
<ul>
<li>Risky customers get approved and actually default</li>
<li>Direct financial losses from unpaid debts</li>
<li>Missed opportunities to offer risk-appropriate pricing</li>
</ul></li>
</ul>
<p><strong>Key Insight:</strong> Better performance metrics focus on the errors that matter most to your business!</p>
</section>
<section id="scenario-1-medical-cancer-screening" class="slide level2 smaller scrollable">
<h2>Scenario 1: Medical Cancer Screening</h2>
<p><strong>You work for a hospital developing an AI system to screen for early-stage cancer.</strong></p>
<p><strong>Business Context:</strong></p>
<ul>
<li>System analyzes medical scans to flag potential cancer cases</li>
<li>Doctors use predictions to decide whether to order additional tests</li>
<li>Early detection dramatically improves patient outcomes</li>
</ul>
<p><strong>Error Costs:</strong></p>
<ul>
<li><strong>False Positive</strong>: Healthy patient flagged as having cancer → $1,500 in unnecessary follow-up tests, patient anxiety</li>
<li><strong>False Negative</strong>: Cancer patient marked as healthy → $50,000+ in delayed treatment costs, potentially life-threatening</li>
</ul>
<div class="callout callout-none no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Question?</strong></p>
</div>
<div class="callout-content">
<p>Which error type should you prioritize minimizing? Why?</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Answer:</strong> Minimize <strong>False Negatives</strong> - Missing cancer cases is life-threatening and costs 30x more than unnecessary tests. Better to have some false alarms than miss actual cancer.</p>
</div>
</section>
<section id="scenario-2-credit-card-fraud-detection" class="slide level2 smaller scrollable">
<h2>Scenario 2: Credit Card Fraud Detection</h2>
<p><strong>You work for a bank building a fraud detection system for credit card transactions.</strong></p>
<p><strong>Business Context:</strong></p>
<ul>
<li>System analyzes transactions in real-time to flag potential fraud</li>
<li>Flagged transactions are automatically blocked from processing</li>
<li>Customer satisfaction and transaction volume are key business metrics</li>
</ul>
<p><strong>Error Costs:</strong></p>
<ul>
<li><strong>False Positive</strong>: Legitimate transaction blocked → Angry customer at checkout, potential customer churn, lost transaction fees</li>
<li><strong>False Negative</strong>: Fraudulent transaction approved → $200 average fraud loss (relatively small compared to transaction volume)</li>
</ul>
<div class="callout callout-none no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Question?</strong></p>
</div>
<div class="callout-content">
<p>Which error type should you prioritize minimizing? Why?</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Answer:</strong> Minimize <strong>False Positives</strong> - Blocking legitimate customers causes immediate frustration and churn. $200 fraud loss is small compared to losing a customer relationship.</p>
</div>
</section>
<section id="scenario-3-marketing-campaign-targeting" class="slide level2 smaller scrollable">
<h2>Scenario 3: Marketing Campaign Targeting</h2>
<p><strong>You work for a company planning targeted email marketing campaigns for product promotions.</strong></p>
<p><strong>Business Context:</strong></p>
<ul>
<li>System predicts which customers are likely to purchase based on promotions</li>
<li>Marketing budget is limited, so targeting efficiency matters</li>
<li>Missing potential customers means lost sales opportunities</li>
</ul>
<p><strong>Error Costs:</strong></p>
<ul>
<li><strong>False Positive</strong>: Send promotion to non-buyer → $2 wasted marketing cost per customer</li>
<li><strong>False Negative</strong>: Miss a potential buyer → $5 lost profit opportunity per customer</li>
</ul>
<div class="callout callout-none no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Question?</strong></p>
</div>
<div class="callout-content">
<p>Should you focus on minimizing false positives, false negatives, or balance both equally? Why?</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Answer:</strong> <strong>Balance both errors</strong> - False negatives cost 2.5x more ($5 vs $2), but both matter for campaign ROI. Need efficiency AND coverage for marketing success.</p>
</div>
</section>
<section id="essential-classification-metrics" class="slide level2 smaller">
<h2>Essential Classification Metrics</h2>
<p><strong>Beyond accuracy, we need metrics that align with business priorities:</strong></p>
<ul>
<li><strong>Precision</strong>: Minimizes false positives (avoid angry customers)</li>
<li><strong>Recall</strong>: Minimizes false negatives (catch critical cases)<br>
</li>
<li><strong>F1-Score</strong>: Balances precision and recall (marketing efficiency)</li>
<li><strong>ROC-AUC</strong>: Measures ranking quality (risk-based pricing)</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Deep Dive in Your Reading</strong></p>
</div>
<div class="callout-content">
<p>Each metric involves important mathematical formulas and trade-offs. <strong>Chapter 24</strong> provides detailed explanations, examples, and business applications you’ll need for Thursday’s lab and upcoming assignments.</p>
<p>Focus on: confusion matrices, the derivative error metrics, and when to use each metric.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="choosing-the-right-metric-for-your-business" class="title-slide slide level1 center" data-background="#43464B">
<h1>Choosing the Right Metric for Your Business</h1>

</section>
<section id="metric-selection-framework" class="slide level2 smaller">
<h2>Metric Selection Framework</h2>
<p><strong>The key question:</strong> What business outcome are you optimizing?</p>
<div class="columns">
<div class="column">
<ul>
<li><strong>Use PRECISION when:</strong>
<ul>
<li>False positives cost more than false negatives</li>
<li>Customer experience is critical</li>
<li><em>Example: Credit card fraud (don’t block legitimate purchases)</em></li>
</ul></li>
<li><strong>Use RECALL when:</strong>
<ul>
<li>False negatives cost more than false positives<br>
</li>
<li>Safety/compliance is critical</li>
<li><em>Example: Medical screening (don’t miss diseases)</em></li>
</ul></li>
</ul>
</div><div class="column">
<ul>
<li><strong>Use F1-SCORE when:</strong>
<ul>
<li>Both error types matter equally</li>
<li>You need balanced performance</li>
<li><em>Example: Marketing targeting (efficiency + coverage)</em></li>
</ul></li>
<li><strong>Use ROC-AUC when:</strong>
<ul>
<li>You need to rank customers by risk</li>
<li>Stratification and pricing decisions</li>
<li><em>Example: Insurance premium tiers</em></li>
</ul></li>
</ul>
</div></div>
</section>
<section id="business-scenario-challenge" class="slide level2 smaller">
<h2>Business Scenario Challenge</h2>
<p><strong>Your turn to be the expert!</strong> For each scenario…</p>
<div class="columns">
<div class="column" style="width:70%;">
<p><strong>Scenarios:</strong></p>
<ol type="1">
<li><strong>Airport Security</strong>: TSA screening for dangerous items</li>
<li><strong>Job Resume Screening</strong>: Initial filter for qualified candidates<br>
</li>
<li><strong>Product Quality Control</strong>: Detecting defective products</li>
<li><strong>Customer Churn Prediction</strong>: Identify customers likely to cancel</li>
<li><strong>Medical Diagnosis</strong>: AI system supporting doctor decisions</li>
</ol>
<div class="callout callout-none no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>For each:</strong></p>
</div>
<div class="callout-content">
<p>Think about which errors you would want to minimize (or the evaluation metrics you’d want to use) and why?</p>
</div>
</div>
</div>
</div><div class="column" style="width:30%;">
<center>
<div id="6minScenarios">

</div>
<script src="_extensions/produnis/timer/timer.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        initializeTimer("6minScenarios", 360, "slide"); 
    });
</script>
</center>
</div></div>
</section>
<section id="scenario-challenge-answers" class="slide level2 smaller scrollable">
<h2>Scenario Challenge: Answers</h2>
<p><strong>Business-aligned metric selection:</strong></p>
<p><strong>1. Airport Security</strong> → <strong>Recall</strong></p>
<ul>
<li>Missing dangerous items = catastrophic</li>
<li>False alarms inconvenient but acceptable</li>
</ul>
<div class="fragment">
<p><strong>2. Job Resume Screening</strong> → <strong>Precision</strong></p>
<ul>
<li>Don’t waste time interviewing unqualified candidates</li>
<li>Can always expand search if needed</li>
</ul>
</div>
<div class="fragment">
<p><strong>3. Product Quality Control</strong> → <strong>Recall</strong></p>
<ul>
<li>Shipping defects damages brand reputation</li>
<li>Better to reject some good products than ship bad ones</li>
</ul>
</div>
<div class="fragment">
<p><strong>4. Customer Churn Prediction</strong> → <strong>F1-Score</strong></p>
<ul>
<li>Need both efficiency (precision) and coverage (recall)</li>
<li>Balance retention costs with intervention effectiveness</li>
</ul>
</div>
<div class="fragment">
<p><strong>5. Medical Diagnosis</strong> → <strong>Recall</strong></p>
<ul>
<li>Missing diseases can be life-threatening</li>
<li>Better to order unnecessary tests than miss conditions</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Pattern:</strong></p>
</div>
<div class="callout-content">
<p>Safety/compliance scenarios prioritize recall, efficiency scenarios prioritize precision, business optimization balances both.</p>
</div>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li><strong>Classification vs.&nbsp;Regression</strong> – Predicting categories requires different algorithms and evaluation approaches</li>
<li><strong>Logistic Regression</strong> – The S-shaped logistic function transforms linear predictions into valid probabilities<br>
</li>
<li><strong>Model Interpretation</strong> – Positive coefficients increase odds; larger coefficients = stronger effects</li>
<li><strong>Beyond Accuracy</strong> – Business-focused metrics (precision, recall, F1, ROC-AUC) align with real costs and priorities</li>
</ul>
</section>
<section id="connection-to-thursdays-lab" class="slide level2">
<h2>Connection to Thursday’s Lab</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>This Week’s Lab Preview</strong></p>
</div>
<div class="callout-content">
<p>In Thursday’s lab, you’ll get hands-on practice with:</p>
<ul>
<li>Building logistic regression models using real medical data to predict cancer</li>
<li>Applying proper data preparation techniques for classification</li>
<li>Evaluating models using precision, recall, F1-score, and ROC-AUC</li>
<li>Making business-aligned evaluation decisions based on error costs</li>
</ul>
<p>Come prepared to apply today’s concepts in a medical diagnosis context!</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="questions-next-steps" class="title-slide slide level1 center" data-background="#43464B">
<h1>Questions &amp; Next Steps</h1>

</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<p><strong>Thursday Lab:</strong> Hands-On Classification with Medical Data</p>
<p><strong>Homework:</strong> Thursday’s lab also serves as this week’s homework assignment</p>
</section>
<section id="any-final-questions" class="slide level2">
<h2>Any Final Questions?</h2>
<ul>
<li>About classification vs.&nbsp;regression?</li>
<li>About logistic regression interpretation?</li>
<li>About evaluation metrics?</li>
<li>About Thursday’s lab?</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Office Hours &amp; Resources</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Office hours (aka Thursday lab): Available for additional support</li>
<li>Discussion board: Post questions about course topics</li>
<li>Lab materials: Available via Canvas</li>
</ul>
</div>
</div>
</div>
</section>
<section class="slide level2">

<center>
<strong>See you Thursday for hands-on classification analysis!</strong>
</center>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>BANA 4080</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="w10_tuesday_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="w10_tuesday_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/appearance/appearance.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="w10_tuesday_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="w10_tuesday_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'appearance': {"hideagain":true,"delay":300,"debug":false,"appearevent":"slidetransitionend","autoappear":false,"autoelements":false,"appearparents":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, Appearance, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>