# (PART) Module 4 {-}

# Overview

The last several lessons gave you a good introduction to building predictive regression models using the Tidymodels construct. However, we haven't discussed how to build predictive classification models. This module will introduce logistic regression, which is very similar to linear regression but for classification problems.  In addition, this module introduces regularized regression, which is a slight twist on both linear and logistic regression.

## Learning objectives

By the end of this module you should be able to:

- Explain how a logistic regression model characterizes the data it is applied to.
- Fit, interpret, and assess the performance of simple and multiple logistic regression models.

## Estimated time requirement

The estimated time to go through the module lessons is about:

* Reading only: 2-3 hours
* Reading + videos: 3-4 hours

## Tasks

```{block, type='todo'}
* Work through the 2 module lessons.
* Upon finishing each lesson take the associated lesson quizzes on Canvas. Be sure to complete the lesson quiz no later than the due date listed on Canvas.
* Check Canvas for this week's lab, lab quiz due date, and any additional content (i.e. in-class material)
```
