# (PART) Module 2 {-}

# Overview

In the last module we discussed the basics of fitting a model. Part of this process included [_creating a model type_](https://bradleyboehmke.github.io/uc-bana-4080/lesson-1b-first-model-with-tidymodels.html#building-models) and we illustrated how to apply linear regression, K-nearest neighbor, and logistic regression models. Yet, we didn't really discuss these algorithms and what they are doing under the hood. We'll turn our attention to that now and we'll start by looking at a fundamental algorithm -- ***linear regression***.

## Learning objectives

By the end of this module you should be able to:

- Explain how a linear regression model characterizes the data it is applied to.
- Fit, interpret, and assess the performance of simple and multiple linear regression models.

## Estimated time requirement

The estimated time to go through the module lessons is about 3 hours.

## Tasks

```{block, type='todo'}
* Work through the 2 module lessons.
* Upon finishing each lesson take the associated lesson quizzes on Canvas. Be sure to complete the lesson quiz no later than the due date listed on Canvas.
* Check Canvas for this week's lab, lab quiz due date, and any additional content (i.e. in-class material)
```
