# (PART) Module 3 {-}

# Overview

The last several lessons gave you a good introduction to building predictive regression models using the Tidymodels construct. However, we haven't discussed how to build predictive classification models. The next module will introduce logistic regression, which is very similar to linear regression but for classification problems.  But before we create our first classification model we're going to introduce two new steps into our modeling process -- feature engineering to make our feature variables more relevant to modeling and resampling procedures to a more accurate and robust generalization error..

## Learning objectives

By the end of this module you should be able to:

- Have a more accurate and robust generalization error for your model by using ___resampling procedures___.
- Make your feature variables more relevant to modeling with ___feature engineering___.

## Estimated time requirement

The estimated time to go through the module lessons is about:

* Reading only: 2-3 hours
* Reading + videos: 3-4 hours

## Tasks

```{block, type='todo'}
* Work through the 2 module lessons.
* Upon finishing each lesson take the associated lesson quizzes on Canvas. Be sure to complete the lesson quiz no later than the due date listed on Canvas.
* Check Canvas for this week's lab, lab quiz due date, and any additional content (i.e. in-class material)
```
