# (PART) Module 4 {-}

# Overview

In the last lesson we discussed regularization and were introduced to the idea of hyperparameters. We learned that we have control over these hyperparameter settings and we need to go through iterations of testing out different values to determine which hyperparameter settings provide the optimal result. However, rather than manually assess different values as we did in the last lesson, we're going to learn how to automate the tuning process for more efficient and effective ***hyperparameter tuning***. Then, we're going to dive into the world of non-linear algorithms by introducing an extension of linear regression called ***multivariate adaptive regression splines***.

## Learning objectives

By the end of this module you should be able to:

- Explain the bias-variance trade-off and apply efficient and effective hyperparameter tuning.
- Apply a multivariate adaptive regression splines to capture non-linear relationships in our data.

## Estimated time requirement

The estimated time to go through the module lessons is about:

* Reading only: 2-3 hours
* Reading + videos: 3-4 hours

## Tasks

```{block, type='todo'}
* Work through the 2 module lessons.
* Upon finishing each lesson take the associated lesson quizzes on Canvas. Be sure to complete the lesson quiz no later than the due date listed on Canvas.
* Check Canvas for this week's lab, lab quiz due date, and any additional content (i.e. in-class material)
```
