# (PART) Module 1 {-}

# Overview

Before introducing specific machine learning (ML) algorithms, it is important that we have a solid understanding of the overall objective of ML algorithms and the common problems they can address. Consequently, this module provides an introduction to ML and starts to introduce parts of the ML modeling process that you’ll routinely see in future modeling lessons.

## Learning objectives

By the end of this module you should be able to:

- Be able to explain the difference between supervised and unsupervised learning.
- Know when a problem is considered a regression or classification problem.
- Split your data into training and test sets.
- Instantiate, train, fit, and evaluate a basic predictive model.

## Estimated time requirement

The estimated time to go through the module lessons is about 3 hours.

## Tasks

```{block, type='todo'}
* Work through the 2 module lessons.
* Upon finishing each lesson take the associated lesson quizzes on Canvas. Be sure to complete the lesson quiz no later than the due date listed on Canvas.
* Check Canvas for this week's lab, lab quiz due date, and any additional content (i.e. in-class material).
```
