project:
  type: book

book:
  title: "BANA 4080: Data Mining"
  author: "Brad Boehmke"
  date: today
  search: true
  sidebar:
    style: docked
  repo-url: https://github.com/bradleyboehmke/uc-bana-4080
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [epub]
  sharing: [twitter]

  chapters:
    - index.qmd
    - part: "Module 1"
      chapters:
        - 01-intro-data-mining.qmd
        - 02-preparing-for-code.qmd
        - 03-python-basics.qmd
    - part: "Module 2"
      chapters:
        - 04-tbd.qmd
    - part: "Appendix"
      chapters:
        - 99-anaconda-install.qmd
        - 99-vscode-install.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    callout-appearance: simple
    number-depth: 2
    mermaid:
      theme: neutral



