project:
  type: book

book:
  title: "BANA 4080: Data Mining"
  author: "Brad Boehmke"
  date: today
  search: true
  sidebar:
    style: docked
  repo-url: https://github.com/bradleyboehmke/uc-bana-4080
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [epub]
  sharing: [twitter]

  chapters:
    - index.qmd
    - part: "Module 1"
      chapters:
        - 01-intro-data-mining.qmd
        - 02-preparing-for-code.qmd
        - 03-python-basics.qmd
    - part: "Module 2"
      chapters:
        - 04-jupyter.qmd
        - 05-data-structures.qmd
        - 06-libraries.qmd
    - part: "Module 3"
      chapters: 
        - 07-importing-data.qmd
        - 08-dataframes.qmd
        - 09-subsetting.qmd
    - part: "Module 4"
      chapters: 
        - 10-manipulating-data.qmd
        - 11_aggregating_data.qmd
        - 12-joining-data.qmd
    - part: "Module 5"
      chapters: 
        - 13-data-viz-pandas.qmd
        - 14-data-viz-matplotlib.qmd
        - 15-data-viz-bokeh.qmd
    - part: "Module 6"
      chapters: 
        - 16-control-statements.qmd
        - 17-iteration-statements.qmd
        - 18-functions.qmd
    - part: "Appendix"
      chapters:
        - 99-anaconda-install.qmd
        - 99-vscode-install.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: superhero
    code-link: true
    callout-appearance: simple
    number-depth: 2
    mermaid:
      theme: neutral



